GET http://localhost:3000/api/usuario

###

GET http://localhost:3000/api/usuario/1

###

POST http://localhost:3000/api/usuario
content-type: application/json

{
"nombre":"Javier", 
"email":"j@j.es", 
"clave":"1234"
}

###

DELETE http://localhost:3000/api/nota/1

###

PUT http://localhost:3000/api/nota/1
content-type: application/json

{
"nombre":"Prueba", 
"texto":"Probando probando", 
"fecha":"10/10/2025", 
"usuario_id":"1"
}